services:
  - type: web
    name: moka-cafee
    runtime: python
    plan: free
    region: oregon
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app -w 4 -b 0.0.0.0:$PORT
